### ISSUE TITLE
Error: Resource for parameter [deviceId] is not found

### ISSUE THREAD

**Issue by nimosunbit** [tylerlong/ringcentral-softphone-js#3]
Hey,

I am trying to use one of my users to register a softphone and getting this error:
`Error: Resource for parameter [deviceId] is not found`

**Comment by tylerlong** [comment]
Could you please post more details? Such as stack trace? 

Any instructions to reproduce the issue?

**Comment by nimosunbit** [comment]
This is the only error I get. I think it relates to specific extensions. When I switched the supervisor, it worked.

**Comment by tylerlong** [comment]
Close it since no reliable way to reproduce.
