### ISSUE TITLE
Saving audio to Linear PCM wave

### ISSUE THREAD

**Issue by theconsummate** [tylerlong/ringcentral-softphone-js#5]
Hello,

I am trying to save the audio stream being received via the Call Supervision API as described in this example: https://github.com/tylerlong/ringcentral-call-supervise-demo/blob/master/index.js#L43

However, when I try to play the file on my computer, I get an Unspecified exception error. The utility exiftool is also unable to read the metadata of the file.

Is there a way to convert the audio encoding of the audio buffer into Linear PCM wav format so that it can be played by a normal audio player.

**Comment by tylerlong** [comment]
> However, when I try to play the file on my computer, I get an Unspecified exception error. The utility exiftool is also unable to read the metadata of the file.

How did you play it and what is the exact error?

**Comment by theconsummate** [comment]
I did afplay <file> on a mac machine and I got "Unspecified exception".

My end goal is to implement Live transcription using Google speech to text on the stream packets which is why I'm trying to the wav conversion. Google's API also throws an error when I re-route the current packets after downsampling from 48kHz to 16kHz.

**Comment by tylerlong** [comment]
I never used afplay. The audio format is this:

```
play -e signed -b 16 -c 1 -r 8000 call.raw
```

You can rename `call.raw` to `call.xxx` where `.xxx` is a supported extension by afplay. Such as `call.wav`. 

> Google's API also throws an error when I re-route the current packets after downsampling from 48kHz to 16kHz.

What is the error?

Somebody tried IBM Waston live transcription and it works: https://medium.com/ringcentral-developers/build-a-real-time-phone-conversation-analytics-455f1d7f0e23

**Comment by tylerlong** [comment]
For this ticket "Saving audio to Linear PCM wave" I think the audio is already Linear PCM wave.

**Comment by theconsummate** [comment]
Hey!

Although the file is playing with the play command you mentioned, nothing is audible. I had tried renaming to "call.wav" but I was still getting the same error.

On Google ASR, I get a `Malordered Data Received. Send exactly one config, followed by audio data.` This might be a helpful reference: https://github.com/googleapis/nodejs-speech/issues/198#issuecomment-480012232
